spring:
  application:
    name: badger-spring-cloud-alibaba-config-client
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.124.15:8848
#      config:
#        server-addr: 192.168.124.15:8848
#        file-extension: yaml

nacos:
  config:
    server-addr: 192.168.124.15:8848
    namespace: 14deb308-442e-4fee-95c0-59e4eaf64964

# 阿波罗 vs nacos





#management:
#  endpoints:
#    web:
#      exposure:

#        include: '*'